GET http://localhost:8080/api/marcas/
###
GET http://localhost:8080/api/marcas/2
###
POST http://localhost:8080/api/marcas/
Content-Type: application/json

{
    "nombre": "NVIDIA"
}

###
POST http://localhost:8080/api/marcas/
Content-Type: multipart/form-data; boundary=XYZ

--XYZ
Content-Disposition: form-data; name="nombre"

RAZER
--XYZ
Content-Disposition: form-data; name="imagen"; filename="nvidiaLogo.png"
Content-Type: image/png

< ../testImages/nvidiaLogo.png
--XYZ--

### Simple update
PATCH http://localhost:8080/api/marcas/27
Content-Type: application/json

{
    "nombre": "RAZER-NOIMAGE"
}

### Update with image
PATCH http://localhost:8080/api/marcas/27
Content-Type: multipart/form-data; boundary=XYZ

--XYZ
Content-Disposition: form-data; name="nombre"

AMD
--XYZ
Content-Disposition: form-data; name="imagen"; filename="amdLogo.png"
Content-Type: image/png

< ../testImages/amdLogo.png
--XYZ--
###
DELETE http://localhost:8080/api/marcas/23