GET http://localhost:8080/api/pedidos/

###
GET http://localhost:8080/api/pedidos/22

### Crear pedido
POST http://localhost:8080/api/pedidos/
Content-Type: application/json

{
  "tipoEntrega": "retiro",
  "tipoPago": "efectivo",
  "cliente": {
    "dni": "10000003",
    "nombre": "Maria",
    "apellido": "Lopez",
    "email": "maria.lopez@example.com",
    "telefono": "+54 9 11 1234 5633",
    "provincia": "Buenos Aires",
    "ciudad": "Córdoba Capital",
    "direccion": "Boulevard Central 103",
    "codigoPostal": "1003"
  },
  "detalle": [
    {
      "cantidad": 1,
      "productoId": 4
    },
    {
      "cantidad": 1,
      "productoId": 6
    }
  ]
}

### Confirmar pedido
PATCH http://localhost:8080/api/pedidos/1
Content-Type: application/json

{
  "estado": "confirmado"
}

### Cancelar pedido
PATCH http://localhost:8080/api/pedidos/21
Content-Type: application/json

{
  "estado": "cancelado"
}

### Validar pedido
POST http://localhost:8080/api/pedidos/validate
Content-Type: application/json

{
  "tipoEntrega": "retiro",
  "tipoPago": "efectivo",
  "detalle": [
    {
      "cantidad": 1,
      "productoId": 4
    },
    {
      "cantidad": 1,
      "productoId": 6
    }
  ]
}
