GET http://localhost:8080/api/pedidos/

###
GET http://localhost:8080/api/pedidos/10

###
POST http://localhost:8080/api/pedidos/
Content-Type: application/json

{
  "tipoEntrega": "retiro",
  "tipoPago": "efectivo",
  "fechaEntrega": "2025-07-01 15:30:00",
  "detalle": [
    {
      "cantidad": 2,
      "productoId": 102
    },
    {
      "cantidad": 1,
      "productoId": 3
    }
  ]
}

###
PATCH http://localhost:8080/api/pedidos/1
Content-Type: application/json

{
  "estado": "confirmado"
}

###
DELETE http://localhost:8080/api/pedidos/1