GET http://localhost:8080/api/productos

### Get products with min price filter
GET http://localhost:8080/api/productos/?page=2

### Get product by ID
GET http://localhost:8080/api/productos/4

### Create product with singular image
POST http://localhost:8080/api/productos
Content-Type: multipart/form-data; boundary=XYZ

--XYZ
Content-Disposition: form-data; name="nombre"

RTX 5090
--XYZ
Content-Disposition: form-data; name="precio"

350000
--XYZ
Content-Disposition: form-data; name="stock"

10
--XYZ
Content-Disposition: form-data; name="marcaId"

163
--XYZ
Content-Disposition: form-data; name="categoriaId"

115
--XYZ
Content-Disposition: form-data; name="images"; filename="nvidiaLogo.png"
Content-Type: image/png

< ../testImages/nvidiaLogo.png
--XYZ--

### Create product with multiple images
POST http://localhost:8080/api/productos
Content-Type: multipart/form-data; boundary=XYZ

--XYZ
Content-Disposition: form-data; name="nombre"

RTX 50901
--XYZ
Content-Disposition: form-data; name="precio"

500000
--XYZ
Content-Disposition: form-data; name="stock"

20
--XYZ
Content-Disposition: form-data; name="marcaId"

163
--XYZ
Content-Disposition: form-data; name="categoriaId"

115
--XYZ
Content-Disposition: form-data; name="images"; filename="amdLogo.png"
Content-Type: image/png

< ../testImages/amdLogo.png
--XYZ
Content-Disposition: form-data; name="images"; filename="nvidiaLogo.png"
Content-Type: image/png

< ../testImages/nvidiaLogo.png
--XYZ--

### Update product with new images
PUT http://localhost:8080/api/productos/5
Content-Type: multipart/form-data; boundary=XYZ

--XYZ
Content-Disposition: form-data; name="nombre"

RTX 10000
--XYZ
Content-Disposition: form-data; name="images"; filename="nvidiaLogo.png"
Content-Type: image/png

< ../testImages/nvidiaLogo.png
--XYZ
Content-Disposition: form-data; name="images"; filename="amdLogo.png"
Content-Type: image/png

< ../testImages/amdLogo.png
--XYZ--

### Update product with new images (while also deleting some)
PUT http://localhost:8080/api/productos/5
Content-Type: multipart/form-data; boundary=XYZ

--XYZ
Content-Disposition: form-data; name="nombre"

RTX 10002
--XYZ
Content-Disposition: form-data; name="imagesToRemove"

13ed392e-6a56-4f8e-80c1-ad90bceb52b9
--XYZ
Content-Disposition: form-data; name="images"; filename="nvidiaLogo.png"
Content-Type: image/png

< ../testImages/nvidiaLogo.png
--XYZ
Content-Disposition: form-data; name="images"; filename="amdLogo.png"
Content-Type: image/png

< ../testImages/amdLogo.png
--XYZ--

### Update product without new images (deleting some)
PUT http://localhost:8080/api/productos/5
Content-Type: multipart/form-data; boundary=XYZ

--XYZ
Content-Disposition: form-data; name="nombre"

RTX 10005
--XYZ
Content-Disposition: form-data; name="imagesToRemove"

b4e9bce2-7679-4aca-a579-1b6a6720373f
--XYZ--

### Update product without new images (keeping all)
PUT http://localhost:8080/api/productos/5
Content-Type: multipart/form-data; boundary=XYZ

--XYZ
Content-Disposition: form-data; name="nombre"

RTX 10010
--XYZ--

### Delete product
DELETE http://localhost:8080/api/productos/513