GET http://localhost:8080/api/productos

###
GET http://localhost:8080/api/productos/?precioMin=120000

###
GET http://localhost:8080/api/productos/7

### Create with singular image
POST http://localhost:8080/api/productos
Content-Type: multipart/form-data; boundary=XYZ

--XYZ
Content-Disposition: form-data; name="nombre"

RTX 5090
--XYZ
Content-Disposition: form-data; name="precio"

350000
--XYZ
Content-Disposition: form-data; name="stock"

10
--XYZ
Content-Disposition: form-data; name="marcaId"

1
--XYZ
Content-Disposition: form-data; name="categoriaId"

3
--XYZ
Content-Disposition: form-data; name="images"; filename="nvidiaLogo.png"
Content-Type: image/png

< ../testImages/nvidiaLogo.png
--XYZ--

### Create with multiple images
POST http://localhost:8080/api/productos
Content-Type: multipart/form-data; boundary=XYZ

--XYZ
Content-Disposition: form-data; name="nombre"

RTX 4090
--XYZ
Content-Disposition: form-data; name="precio"

500000
--XYZ
Content-Disposition: form-data; name="stock"

20
--XYZ
Content-Disposition: form-data; name="marcaId"

1
--XYZ
Content-Disposition: form-data; name="categoriaId"

3
--XYZ
Content-Disposition: form-data; name="images"; filename="amdLogo.png"
Content-Type: image/png

< ../testImages/amdLogo.png
--XYZ
Content-Disposition: form-data; name="images"; filename="nvidiaLogo.png"
Content-Type: image/png

< ../testImages/nvidiaLogo.png
--XYZ--

###
DELETE http://localhost:8080/api/productos/13