GET http://localhost:8080/api/productos

###
GET http://localhost:8080/api/productos/?precioMin=qowqow

###
GET http://localhost:8080/api/productos/1023

###
POST http://localhost:8080/api/productos
Content-Type: multipart/form-data; boundary=XYZ

--XYZ
Content-Disposition: form-data; name="nombre"

RTX 3060
--XYZ
Content-Disposition: form-data; name="images"; filename="amdLogo.png"
Content-Type: image/png

< ../testImages/amdLogo.png
--XYZ
Content-Disposition: form-data; name="images"; filename="nvidiaLogo.png"
Content-Type: image/png

< ../testImages/nvidiaLogo.png
--XYZ--

###
DELETE http://localhost:8080/api/productos/9249

###
PATCH http://localhost:8080/api/productos/1439
Content-Type: application/json

{
    "stock": 50
}